
-- This custom view does the follow: 
-- Turns the given dataset into user-week level with one row per week per user and organisation
-- Removes outliers
-- Transforms fields to more readable formats

CREATE OR REPLACE VIEW `accurx-490419.accurx.accurx_activity_base` AS
(
-- User base CTE to calculate sign-up date for each user
WITH user_base AS 
(
SELECT ANONYMOUS_USER_ID, 
MIN(EXTRACT(DATE FROM ACTIVITY_WEEK)) AS SIGNUP_WEEK
FROM `accurx-490419.accurx.WEB_ACTIVITY_WEEK`
GROUP BY 1  
),
-- Activity week base CTE to calculate weekly activity metrics per user
week_base AS 
(
SELECT a.ANONYMOUS_USER_ID, 
u.SIGNUP_WEEK, 
EXTRACT(DATE FROM ACTIVITY_WEEK) AS ACTIVITY_WEEK, 
DATE_DIFF( EXTRACT (DATE FROM ACTIVITY_WEEK), u.SIGNUP_WEEK, WEEK) AS WEEKS_SINCE_SIGNUP, --Calculates weeks since sign-up for each week user is active

--Activity Intensity Metrics
SUM(TOT_ACTIVITY_WEEK) AS TOT_ACTIVITY_WEEK, 
SUM(CASE WHEN ACTIVITY_NAME = 'Other' THEN TOT_ACTIVITY_WEEK ELSE 0 END) AS TOT_OTHER_ACTIVITY, --Extracting 'Other' activities from total activity
SUM(CASE WHEN ACTIVITY_NAME != 'Other' THEN TOT_ACTIVITY_WEEK ELSE 0 END) AS TOT_KEY_ACTIVITY, --Extracting 'Key' activities from total activity

--Flatenning ACTIVITY_NAME type field to a single row
SUM(CASE WHEN ACTIVITY_NAME = 'PatientMessageSend Button Click Web' THEN TOT_ACTIVITY_WEEK ELSE 0 END) AS PATIENT_MESSAGES_SENT, 
SUM(CASE WHEN ACTIVITY_NAME = 'ClinicianMessageSend Button Click Web' THEN TOT_ACTIVITY_WEEK ELSE 0 END) AS CLINICIAN_MESSAGES_SENT, 
SUM(CASE WHEN ACTIVITY_NAME = 'PatientVideoInviteSend Button Click Web' THEN TOT_ACTIVITY_WEEK ELSE 0 END) AS PATIENT_VIDEO_INVITES_SENT,

--Flatenning ORGANISATION_CARE_CLASSIFICATION type field to a single row
MAX(CASE WHEN ORGANISATION_CARE_CLASSIFICATION='PRIMARY' THEN 1 ELSE 0 END) AS PRIMARY_CARE_ACTIVITY, 
MAX(CASE WHEN ORGANISATION_CARE_CLASSIFICATION='SECONDARY' THEN 1 ELSE 0 END) AS SECONDARY_CARE_ACTIVITY, 

--Flatenning PLATFORM type field to a single row
MAX(CASE WHEN PLATFORM='web' THEN 1 ELSE 0 END) AS WEB_ACTIVITY, 
MAX(CASE WHEN PLATFORM='mobile' THEN 1 ELSE 0 END) AS MOBILE_ACTIVITY, 
MAX(CASE WHEN PLATFORM='desktop' THEN 1 ELSE 0 END) AS DESKTOP_ACTIVITY

FROM `accurx-490419.accurx.WEB_ACTIVITY_WEEK` a
LEFT JOIN user_base u 
ON u.ANONYMOUS_USER_ID = a.ANONYMOUS_USER_ID
GROUP BY 1,2,3,4
)
SELECT ANONYMOUS_USER_ID,SIGNUP_WEEK, ACTIVITY_WEEK, WEEKS_SINCE_SIGNUP, TOT_ACTIVITY_WEEK, TOT_OTHER_ACTIVITY, TOT_KEY_ACTIVITY,

-- Turning TOT_KEY_ACTIVITY count into level for readability 
CASE WHEN TOT_KEY_ACTIVITY=0 THEN '0'
WHEN TOT_KEY_ACTIVITY = 1 THEN '1'
WHEN TOT_KEY_ACTIVITY = 2 THEN '2'
WHEN TOT_KEY_ACTIVITY = 3 THEN '3'
WHEN TOT_KEY_ACTIVITY = 4 THEN '4'
WHEN TOT_KEY_ACTIVITY = 5 THEN '5'
ELSE '5+' END AS TOT_KEY_ACTIVITY_LEVEL, 

-- Turning ORGANISATION_CARE_CLASSIFICATION indicators into text field for readability 
CASE WHEN PRIMARY_CARE_ACTIVITY=1 AND SECONDARY_CARE_ACTIVITY = 0 THEN 'PRIMARY_CARE' 
WHEN PRIMARY_CARE_ACTIVITY=0 AND SECONDARY_CARE_ACTIVITY = 1 THEN 'SECONDARY_CARE' 
WHEN PRIMARY_CARE_ACTIVITY=1 AND SECONDARY_CARE_ACTIVITY = 1 THEN 'PRIMARY_AND_SECONDARY_CARE' 
ELSE NULL END AS ORGANISATION_CARE_CLASSIFICATION,

-- Turning ACTIVITY_NAME indicators into text field for readability 
CASE WHEN PATIENT_MESSAGES_SENT>0 AND CLINICIAN_MESSAGES_SENT = 0 AND PATIENT_VIDEO_INVITES_SENT = 0 THEN 'PATIENT_MESSAGES_SENT' 
WHEN PATIENT_MESSAGES_SENT = 0 AND CLINICIAN_MESSAGES_SENT > 0 AND PATIENT_VIDEO_INVITES_SENT = 0 THEN 'CLINICIAN_MESSAGES_SENT' 
WHEN PATIENT_MESSAGES_SENT=0 AND CLINICIAN_MESSAGES_SENT = 0 AND PATIENT_VIDEO_INVITES_SENT > 0 THEN 'PATIENT_VIDEO_INVITES_SENT' 
WHEN PATIENT_MESSAGES_SENT=0 AND CLINICIAN_MESSAGES_SENT = 0 AND PATIENT_VIDEO_INVITES_SENT = 0 THEN NULL 
ELSE 'MULTIPLE_KEY_ACTIVITIES' END AS KEY_ACTIVITY_TYPE, 

-- Turning PLATFORM indicators into text field for readability 
CASE WHEN WEB_ACTIVITY=1 AND MOBILE_ACTIVITY = 0 AND DESKTOP_ACTIVITY = 0 THEN 'WEB'
WHEN WEB_ACTIVITY=0 AND MOBILE_ACTIVITY = 1 AND DESKTOP_ACTIVITY = 0 THEN 'MOBILE'
WHEN WEB_ACTIVITY=0 AND MOBILE_ACTIVITY = 0 AND DESKTOP_ACTIVITY = 1 THEN 'DESKTOP'
WHEN WEB_ACTIVITY=0 AND MOBILE_ACTIVITY = 0 AND DESKTOP_ACTIVITY = 0 THEN NULL
ELSE 'MULTIPLE' END AS PLATFORM
FROM week_base
WHERE TOT_KEY_ACTIVITY < 100 -- Filtering out users with 100+ key actions in a week
)



