-- The purpose of this summarise activation and retention activity on a user level based on weekly activity data 


CREATE OR REPLACE VIEW `accurx-490419.accurx.activity_summary` AS
WITH max_week AS (
  SELECT
    MAX(ACTIVITY_WEEK) AS MAX_ACTIVITY_WEEK
  FROM `accurx-490419.accurx.accurx_activity_base`
),
activation_base AS 
(
SELECT ANONYMOUS_USER_ID, SIGNUP_WEEK,
TOT_ACTIVITY_WEEK AS SIGNUP_TOT_ACTIVITY,
TOT_OTHER_ACTIVITY AS SIGNUP_TOT_OTHER_ACTIVITY, 
TOT_OTHER_ACTIVITY_LEVEL AS SIGNUP_TOT_OTHER_ACTIVITY_LEVEL,
TOT_KEY_ACTIVITY AS SIGNUP_TOT_KEY_ACTIVITY, 
TOT_KEY_ACTIVITY_LEVEL AS SIGNUP_TOT_KEY_ACTIVITY_LEVEL,
PROPORTION_KEY_ACTIVITY AS SIGNUP_PROPORTION_KEY_ACTIVITY,
PRIMARY_CARE_ACTIVITY AS SIGNUP_PRIMARY_CARE_ACTIVITY,
SECONDARY_CARE_ACTIVITY AS SIGNUP_SECONDARY_CARE_ACTIVITY,
ORGANISATION_CARE_CLASSIFICATION AS SIGNUP_ORGANISATION_CARE_CLASSIFICATION , 
PATIENT_MESSAGES_SENT AS SIGNUP_PATIENT_MESSAGES_SENT, 
CLINICIAN_MESSAGES_SENT AS SIGNUP_CLINICIAN_MESSAGES_SENT, 
PATIENT_VIDEO_INVITES_SENT AS SIGNUP_PATIENT_VIDEO_INVITES_SENT, 
KEY_ACTIVITY_TYPE AS SIGNUP_KEY_ACTIVITY_TYPE,
WEB_ACTIVITY AS SIGNUP_WEB_ACTIVITY, 
MOBILE_ACTIVITY AS SIGNUP_MOBILE_ACTIVITY , 
DESKTOP_ACTIVITY AS SIGNUP_DESKTOP_ACTIVITY,
PLATFORM AS SIGNUP_PLATFORM, 
CASE WHEN TOT_KEY_ACTIVITY>0 THEN 'KEY ACTIVITY PERFORMED' ELSE 'KEY ACTIVITY NOT PERFORMED' END AS ACTIVATION_ACTIVITY_PERFORMED
FROM `accurx-490419.accurx.accurx_activity_base_long` 
WHERE WEEKS_SINCE_SIGNUP = 0
), 
-- on a user level with one row per user, assigns flags to calculate retention easily later
retention_base AS
(
SELECT ANONYMOUS_USER_ID, 
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 1 WEEK) THEN 1 ELSE 0 END) AS WEEK2_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 2 THEN 1 ELSE 0 END) AS WEEK2_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 3 WEEK) THEN 1 ELSE 0 END) AS WEEK4_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 4 THEN 1 ELSE 0 END) AS WEEK4_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 5 WEEK) THEN 1 ELSE 0 END) AS WEEK6_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 6 THEN 1 ELSE 0 END) AS WEEK6_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 7 WEEK) THEN 1 ELSE 0 END) AS WEEK8_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 8 THEN 1 ELSE 0 END) AS WEEK8_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 9 WEEK) THEN 1 ELSE 0 END) AS WEEK10_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 10 THEN 1 ELSE 0 END) AS WEEK10_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 11 WEEK) THEN 1 ELSE 0 END) AS WEEK12_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 12 THEN 1 ELSE 0 END) AS WEEK12_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 13 WEEK) THEN 1 ELSE 0 END) AS WEEK14_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 14 THEN 1 ELSE 0 END) AS WEEK14_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 15 WEEK) THEN 1 ELSE 0 END) AS WEEK16_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 16 THEN 1 ELSE 0 END) AS WEEK16_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 17 WEEK) THEN 1 ELSE 0 END) AS WEEK18_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 18 THEN 1 ELSE 0 END) AS WEEK18_RETAINED,
MAX(CASE WHEN SIGNUP_WEEK <= DATE_SUB(m.MAX_ACTIVITY_WEEK, INTERVAL 19 WEEK) THEN 1 ELSE 0 END) AS WEEK20_ELIGIBLE,
MAX(CASE WHEN WEEKS_SINCE_SIGNUP = 20 THEN 1 ELSE 0 END) AS WEEK20_RETAINED
FROM `accurx-490419.accurx.accurx_activity_base_long`
CROSS JOIN max_week m
GROUP BY 1  
)
SELECT
a.*,
r.WEEK2_ELIGIBLE,
r.WEEK2_RETAINED,
r.WEEK4_ELIGIBLE,
r.WEEK4_RETAINED,
r.WEEK6_ELIGIBLE,
r.WEEK6_RETAINED,
r.WEEK8_ELIGIBLE,
r.WEEK8_RETAINED,
r.WEEK10_ELIGIBLE,
r.WEEK10_RETAINED,
r.WEEK12_ELIGIBLE,
r.WEEK12_RETAINED,
r.WEEK14_ELIGIBLE,
r.WEEK14_RETAINED,
r.WEEK16_ELIGIBLE,
r.WEEK16_RETAINED,
r.WEEK18_ELIGIBLE,
r.WEEK18_RETAINED,
r.WEEK20_ELIGIBLE,
r.WEEK20_RETAINED,
FROM activation_base a
LEFT JOIN retention_base r
  ON r.ANONYMOUS_USER_ID = a.ANONYMOUS_USER_ID;
