-- Adhoc query to calculate retention rate by factors 
SELECT 
ACTIVATION_STATUS,
COUNT(DISTINCT ANONYMOUS_USER_ID) AS USERS, -- Size of entire cohort
-- Week 2 Retention Metrics
COUNT(DISTINCT CASE WHEN WEEK2_ELIGIBLE = 1 THEN ANONYMOUS_USER_ID END) AS WEEK2_ELIGIBLE_USERS, -- Size of eligible cohort for reference
ROUND(COUNT (DISTINCT CASE WHEN WEEK2_RETAINED=1 THEN ANONYMOUS_USER_ID ELSE NULL END)/NULLIF(COUNT (DISTINCT CASE WHEN WEEK2_ELIGIBLE=1 THEN ANONYMOUS_USER_ID ELSE NULL END),0)*100,2) AS WEEK2_RETENTION_RATE, -- Retention rate calculated by dividing retained users by eligible users
-- Week 4 Retention Metrics
COUNT(DISTINCT CASE WHEN WEEK4_ELIGIBLE = 1 THEN ANONYMOUS_USER_ID END) AS WEEK4_ELIGIBLE_USERS, -- Size of eligible cohort for reference
ROUND(COUNT (DISTINCT CASE WHEN WEEK4_RETAINED=1 THEN ANONYMOUS_USER_ID ELSE NULL END)/NULLIF(COUNT (DISTINCT CASE WHEN WEEK4_ELIGIBLE=1 THEN ANONYMOUS_USER_ID ELSE NULL END),0)*100,2) AS WEEK4_RETENTION_RATE, -- Retention rate calculated by dividing retained users by eligible users
-- Week 8 Retention Metrics
COUNT(DISTINCT CASE WHEN WEEK8_ELIGIBLE = 1 THEN ANONYMOUS_USER_ID END) AS WEEK8_ELIGIBLE_USERS, -- Size of eligible cohort for reference
ROUND(COUNT (DISTINCT CASE WHEN WEEK8_RETAINED=1 THEN ANONYMOUS_USER_ID ELSE NULL END)/NULLIF(COUNT (DISTINCT CASE WHEN WEEK8_ELIGIBLE=1 THEN ANONYMOUS_USER_ID ELSE NULL END),0)*100,2) AS WEEK8_RETENTION_RATE, -- Retention rate calculated by dividing retained users by eligible users
-- Week 12 Retention Metrics
COUNT(DISTINCT CASE WHEN WEEK12_ELIGIBLE = 1 THEN ANONYMOUS_USER_ID END) AS WEEK12_ELIGIBLE_USERS, -- Size of eligible cohort for reference
ROUND(COUNT (DISTINCT CASE WHEN WEEK12_RETAINED=1 THEN ANONYMOUS_USER_ID ELSE NULL END)/NULLIF(COUNT (DISTINCT CASE WHEN WEEK12_ELIGIBLE=1 THEN ANONYMOUS_USER_ID ELSE NULL END),0)*100,2) AS WEEK12_RETENTION_RATE, -- Retention rate calculated by dividing retained users by eligible users
-- Week 16 Retention Metrics
COUNT(DISTINCT CASE WHEN WEEK16_ELIGIBLE = 1 THEN ANONYMOUS_USER_ID END) AS WEEK16_ELIGIBLE_USERS, -- Size of eligible cohort for reference
ROUND(COUNT (DISTINCT CASE WHEN WEEK16_RETAINED=1 THEN ANONYMOUS_USER_ID ELSE NULL END)/NULLIF(COUNT (DISTINCT CASE WHEN WEEK16_ELIGIBLE=1 THEN ANONYMOUS_USER_ID ELSE NULL END),0)*100,2) AS WEEK16_RETENTION_RATE, -- Retention rate calculated by dividing retained users by eligible users
FROM `accurx-490419.accurx.activity_summary`
GROUP BY 1
ORDER BY 1

